name: Auto Link and Close Issues

on:
  pull_request:
    types: [opened, edited, closed, reopened]

jobs:
  link_and_close_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Title for Issue Link
        id: check-pr-title
        run: |
          PR_TITLE=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
          ISSUE_NUMBER=$(echo "$PR_TITLE" | grep -oE '\b(feat|defect) kitty_[0-9]+\b' | grep -oE '[0-9]+')
          echo "::set-output name=issue_number::$ISSUE_NUMBER"

      - name: Comment on Issue with PR Link
        if: steps.check-pr-title.outputs.issue_number != ''
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue_number } = context.payload.pull_request;
            const issueTitle = context.payload.pull_request.title;
            const issueLink = `#${issue_number}`;
            const commentBody = `PR ${issueLink} (${issueTitle}) is related to this issue.`;
            github.issues.createComment({
              issue_number: ${{ steps.check-pr-title.outputs.issue_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });

      - name: Close Issue on PR Merge
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue_number } = context.payload.pull_request;
            github.issues.update({
              issue_number: ${{ steps.check-pr-title.outputs.issue_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed'
            });
