name: Linting

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    name: Lint checks before merging PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Lint code
        run: yarn lint
